version: "3.3"

services:
  id:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    entrypoint: ["/bin/bash", "/iD/launch"]
    volumes:
      - ${ID_PROJECT_DIR:-.}:/iD
